# the K-D ratio is configurable to what you want it to be
# the following placeholders exists:
# &k - kills
# &d - deaths
# &s - current streak value
# &m - max streak value

MySQL: false
MySQLhost: host
MySQLuser: user
MySQLpass: pw
MySQLdb: db
MySQLport: 3306
MySQLtable: pvpstats
MySQLkilltable: pvpkillstats

PVPArena: false
checkabuse: true
updatecheck: true
autodownload: true
tracker: true
collectprecise: true
clearonstart: true
kdcalculation: '&k/(&d+1)'
ignoreworlds:
- doNotTrack