name: pvpstats
main: praxis.slipcor.pvpstats.PVPStats
version: 0.6.7
author: slipcor
soft-depends: pvparena
website: http://dev.bukkit.org/server-mods/pvp-stats/
commands:
    pvpstats:
        description: handle PvP stats
        aliases: stats
permissions:
    pvpstats.reload:
        description: Ability to reload
        default: op
    pvpstats.cleanup:
        description: Ability to cleanup
        default: op
    pvpstats.wipe:
        description: Ability to wipe
        default: op
    pvpstats.count:
        description: Permission to be counted
        default: true
    pvpstats.top:
        description: Permission to get global stats
        default: true
